name: Workflow Scan Action
author: "rcowsill"
description: Scan GitHub Actions workflow files with CodeQL

inputs:
  data-dir-name:
    description: Name of the directory which will hold data needed by the action
    default: workflow-scan-action-data
  extra-queries:
    description: Comma-separated list of additional queries to run
    default: ""

runs:
  using: composite
  steps:
    - name: Configure CodeQL for workflow security scanning
      run: . "$GITHUB_ACTION_PATH/setup.sh"
      shell: bash
      env:
        DATA_DIR_NAME: ${{ inputs.data-dir-name }}
        EXTRA_QUERIES: ${{ inputs.extra-queries }}

    - uses: github/codeql-action/init@v1
      with:
        config-file: ${{ env.WSA_CONFIG_PATH }}
        queries: ${{ env.WSA_QUERIES }}
        languages: javascript

    - uses: github/codeql-action/analyze@v1

branding:
  icon: search
  color: gray-dark
